---
title: "reading data from the web"
author: "Luan Mengxiao"
date: 2023-10-12
output: github_document
---

load the necessary libraries

```{r}
library(tidyverse)
library(rvest)
library(httr)
```

import NSDUH data

```{r}
nsduh_url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"
nsduh_html = read_html(nsduh_url)

nsduh_html
```

```{r}
nsduh_html |>
  html_table()
```

```{r}
marj_use_df = 
  nsduh_html |>
  html_table() |>
  first() |>
  slice(-1)

marj_use_df
```

import star wars

```{r}
swm_url  = 
  "https://www.imdb.com/list/ls070150896/"

swm_html = read_html(swm_url)
```

```{r}
swm_title_vec = 
  swm_html |>
  html_elements(".lister-item-header a") |>
  html_text()

swm_gross_rev_vec = 
  swm_html |>
  html_elements(".text-small:nth-child(7) span:nth-child(5)") |>
  html_text()

swm_runtime_vec = 
  swm_html |>
  html_elements(".runtime") |>
  html_text()

swm_df = 
  tibble(
    title = swm_title_vec,
    gross = swm_gross_rev_vec,
    runtime = swm_runtime_vec)

swm_df
```

API: get data from NYC

```{r}
nyc_water_df = 
  GET("https://data.cityofnewyork.us/resource/ia2d-e54m.csv") |>
  content("parsed")
```

```{r}
brfss_df = 
  GET(
    "https://data.cdc.gov/resource/acme-vg9e.csv",
    query = list("$limit" = 5000)) |>
  content("parsed")
```

```{r}
poke_df = 
  GET("https://pokeapi.co/api/v2/pokemon/ditto") |>
  content()
```

